#!/usr/bin/env bash

for arg in "$@" ; do

	case "${arg}" in
		--bash)
			printf '%s\n' '__fzf_list_hosts() { printf "myServer" ; }'
			exit 0
		;;

		*"Kill"*)
			printf 'Yes'
			exit 0
		;;
	esac
done

printf '%b' "${FZF_MOCK_OUTPUT}"
